name: 'Honeybadger Deploy Action'
description: 'Send deployment notifications to the Honeybadger API'
branding:
  icon: 'globe'
  color: 'orange'
inputs:
  api_key:
    description: 'The Honeybadger project API key'
    required: true
  environment:
    description: 'The deployment environment. Defaults to production.'
    required: false
    default: 'production'
  revision:
    description: 'The revision to deploy. Defaults to git hash on this repository.'
    required: false
  repository:
    description: 'The repository to deploy. Defaults to git hash on this repository.'
    required: false
  endpoint:
    description: 'The deploy submission endpoint. Only used for testing'
    required: false
    default: "https://api.honeybadger.io/v1/deploys"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api_key }}
    - ${{ inputs.environment }}
    - ${{ inputs.revision }}
    - ${{ inputs.repository }}
    - ${{ inputs.endpoint }}
